name: matrix
on: push

jobs:
  Node-versions:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node_version: [16, 18, 19]
        include:
          - os: ubuntu-latest
            node_version: 18
            ubuntu_20: "true"
        exclude:
          - os: ubuntu-latest
            node_version: 16
          - os: macos-latest
            node_version: 14
    runs-on: ${{ matrix.os }}
    env:
      UBUNTU_8: ${{ matrix.ubuntu_20 }}
    steps:
      - name: Node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: After Setup-node node version
        run: |
          node -v
          echo $UBUNTU_8
